# Generated by Django 5.0.1 on 2024-01-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organize_your_pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledate',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
